# install-task.ps1 -- registers the MagpilotAgent scheduled task at user
# logon. Invoked by magpilot.iss at install time. Idempotent: replaces any
# existing task with the same name.
#
# Runs the installed agent EXE as the interactive user (NOT SYSTEM) so it
# can read the user's ~/.copilot/ profile (auth tokens, settings.json,
# session-state). Loads MAGPILOT_HUB_URL etc. from the installer-written
# magpilot.env file.

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$InstallDir,

    [string]$TaskName = 'MagpilotAgent'
)

$ErrorActionPreference = 'Stop'

$agentExe = Join-Path $InstallDir 'agent\Magpilot.Agent.exe'
$envFile  = Join-Path $InstallDir 'config\magpilot.env'

if (-not (Test-Path $agentExe)) {
    Write-Error "Agent executable not found at $agentExe"
    exit 1
}

# The scheduled task has no env-file mechanism, so we wrap the agent in a
# pwsh -Command that loads magpilot.env and exec's the agent. This file
# gets regenerated every install run so it stays in sync with the env.
$wrapperPath = Join-Path $InstallDir 'agent\start.ps1'
$wrapperBody = @"
# Auto-generated by install-task.ps1. Do not edit.
`$ErrorActionPreference = 'Stop'
`$envFile = '$envFile'
if (Test-Path `$envFile) {
    Get-Content `$envFile | ForEach-Object {
        `$line = `$_.Trim()
        if (`$line -and -not `$line.StartsWith('#')) {
            `$eq = `$line.IndexOf('=')
            if (`$eq -gt 0) {
                `$key = `$line.Substring(0, `$eq)
                `$val = `$line.Substring(`$eq + 1)
                Set-Item "Env:`$key" `$val
            }
        }
    }
}
# Bind to all interfaces on TCP 5099 (LAN; firewall.ps1 handles the rule).
`$env:ASPNETCORE_URLS = 'http://0.0.0.0:5099'
& '$agentExe'
"@
Set-Content -Path $wrapperPath -Value $wrapperBody -Encoding UTF8

# Resolve the interactive user. SYSTEM-launched installer needs us to look
# up the *console* user, not whoever launched powershell.exe.
$consoleUser = (Get-CimInstance -ClassName Win32_ComputerSystem).UserName
if (-not $consoleUser) {
    # Fallback: use the user whose env we loaded ($env:USERNAME).
    $consoleUser = "$env:USERDOMAIN\$env:USERNAME"
}

Write-Host "Registering scheduled task '$TaskName' as $consoleUser"

# Tear down any prior registration so we get a clean update.
Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue | ForEach-Object {
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$action = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$wrapperPath`""

$trigger = New-ScheduledTaskTrigger -AtLogOn -User $consoleUser

$principal = New-ScheduledTaskPrincipal `
    -UserId $consoleUser `
    -LogonType Interactive `
    -RunLevel Limited

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero)

Register-ScheduledTask -TaskName $TaskName `
    -Action $action -Trigger $trigger -Principal $principal -Settings $settings | Out-Null

Write-Host "Starting $TaskName..."
Start-ScheduledTask -TaskName $TaskName

Start-Sleep -Seconds 4

$info = Get-ScheduledTaskInfo -TaskName $TaskName
Write-Host "  LastRunTime:    $($info.LastRunTime)"
Write-Host "  LastTaskResult: $($info.LastTaskResult)"
